### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ziigaa** [0sand/Blackjack#1]
Projekti ladattu 5.2.2017 klo 23.01.

Koodi oli varsin helppolukuista ja sitä oli helppo seurata. Kaikki oli mielestäni toteutettu hyvin elegantilla ja tehokkaalla tavalla. Turhaa koodia ja ylimääräisiä monimutkaisuuksia on väistelty taitavasti, koska sellaista yritin etsiä ja ainoat, mitkä onnistuin näkemään olivat if-lausekkeiden rakenteet returnin yhteydessä, esimerkiksi shouldIshuffleDeck-metodin, sisällön saisi lyhyempään muotoon, joka olisi yksinkertaisesti:
return deck.cardsLeft() == 0;
Tosin if-rakenne on myös selkeä ja helppolukuinen. Varsinaisia virheitä koodissa ei ollut.

Logiikka näyttää toimivalta. Testit toiminnallisuuksille olivat järkeviä ja menivät testattaessa kaikki läpi. Pit ja checkstyle myös kunnossa.

Koodi itsessään on hyvää, mutta koska tässä on tarkoituksena keksiä huomautettavaa, niin seuaavia seikkoja tähän laitan:
Camelcase näyttää osittain unohtuneen GUI-osuudesta.
Main.javassa ja DeckTest.javassa on turhia importteja.
Card-luokan suit ja value muuttujista sekä Game-luokan deck, player1 ja dealer muuttujista voisi tehdä final-arvoja.

Eli kaikenkaikkiaan koodi oli hyvää ja huomautettavaa ei tainnut tulla muuta kuin muotoseikoista. Graafinen käyttöliittymä vielä toistaiseksi ei ollut valmis ja tuo tulee todennäköisesti vähän vaatimaan malttia rakennella, joten tsemppiä jatkolle ja kiitokset koodin selkeydestä! :)

**Comment by 0sand** [comment]
Kiitos palauteesta. Nyt on olemassa ensimmäinen toimiva versio. Aika alkeelinen, mutta toimii.
