### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Sadelise** [0sand/Blackjack#2]
Ladattu 18.2.17 klo 15:14

Koodi on yleisesti hyvää, luokat jaettu kivasti paketteihin ja omaavat jonkun tehtävän. Metodit ovat sopivan pituisia ja nimetty kuvaavasti. 

Joitain juttuja joihin kiinnittäisin huomioita:
- Koodin laatuvaatimuksissa (https://github.com/javaLabra/Javalabra2017-3/blob/master/ohjeet/Koodin-laatuvaatimukset.md) mainitaan, ettei ohjelma saa missään vaiheessa printata Exceptioneita komentoriville. Luokassa Deck metodissa dealCard() näin voisi mahdollisesti käydä, jos jokin menee vinoon. Tosin en ole itsekään ihan varma, että mikä käytäntö on, voiko se olla teoriassa mahdollista jos niin ei kuitenkaan tule koskaan käymään? 

- Deck luokan equals metodi hämmentää, koska siinä käytetään lopulta oikeastaan vain Array luokan valmista equals metodia. En toki ole 100:sesti tutustunut siihen miten equals metodia koodissasi käytetään. Equals() myös tarvitsee aina kaverikseen hashCode metodin, koska sen avulla voidaan määrittää juuri tietyt (samat) hajautusarvot tietynlaisille olioille, kun taas normaalisti olion eri ilmentymille luodaan automaattisesti aina eri hajautusarvot vaikka niillä olisi samat arvot muuttujissa. Tämä ristiriita equalsin ja hajautusarvojen välillä voi kuulemma johtaa outoihin bugeihin. Etenkin card luokassa hashCode() metodi olisi hyvä equals()in kaveriksi, koska luomillasi korteilla ei joka tapauksessa ole olemassa mitään omaa hajautusarvo-metodia toisin kuin Arrays-olioilla varmaankin on.

Lisäksi hassuja pikkujuttuja:
- Metodeissa on rivivälejä siellä täällä, jotka ehkä tarpeettomasti pidentävät joitain luokkia. 
-  Voisi käyttää myös tai:ta (||) if lauseissa silloin kun palautusarvo on joka tapauksessa identtinen kummankin ehdon seurauksena. Siten saisi vähemmän iffejä (Card equals()).
- Luokassa Card, metodissa getFileName on käytetty samaa nimeä paikalliselle muuttujalle, joka on jo luokkamuuttujalla (String value).
- Koodiin on jäänyt turhia importteja aika paljon.

Kokonaisuudessaan koodi tuntuu toimivan hienosti ja siinä on mukava määrä testejä, jotka kaikki menevät myös läpi. Peli myös näyttää kivalta, vaikka yläreunan tekstit voisivat olla hiukan selkeämmin erotellut, niin olisi helpompi nopeasti vilkaisemalla nähdä tiedot. Hassusti peli antaa laittaa panokseksi 0, mikä on aika reilua kasinolta, vaikka ei siitä voittoakaan tipu! :D Tietty mukavaa, ettei pelaamisen tarvitse loppua vaikka rahat onkin menetetty.

**Comment by 0sand** [comment]
Kiitos hyvästä palautteesta. Luokan deck metodia tein oikestaan vaan testausta varten. Muuten sitä ei tarvita. Pitää varmaan vähän taas palauttaa mieleen ohjelmoinin jatkukurssin asioista.
Tulevaisuudessa ei tule olemaan mahdollista pelata kun rahat loppuu mutta vielä onnistuu :)
